### ISSUE TITLE
Помоги, пожалуйста!

### ISSUE THREAD

**Issue by NevinTure** [bezlla/FoxfordHack#2]
Привет, я ноль в программировании, но хотел бы получить курсы. Можешь, пожалуйста, записать ролик какой-нибудь или подробно описать, как воспользоваться твоей библиотекой. Пара месяцев до ЕГЭ хотелось бы, подучиться на фоксфорде)

**Comment by aforesaid** [comment]
Без навыков программирования эта библиотека бесполезна. Здесь, увы, ни чем не могу помочь.
